version: "3.9"
services:
  lingo-partners-db:
    image: postgres
    restart: always
    container_name: lingo-partners-db
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes: 
      - postgres:/data/postgres

volumes:
  postgres: